#String Hace Referencia A Texto Podemos Guardar Direcciones, Apellidos Entre Otros Datos Pero Siempre Sera Texto.
Variable = "Hola Mundo"
#Number (Numero Entero) Int 
Numero = 42
#Para Indicar Que Vamos A Separar Un Numero De Su Parte Entera De Sus Fracciones Vamos A Utilizar Un . La Parte Izquierda Es La Entera Y La Derecha Los Decimales Se Le Conoce Como Float.
Decimal = 10.5
#Cuando Algo Es Si.
Verdadero = True
#Cuando Algo Es No.
Falso = False