Texto = "Hola Mundo"
# Upper Convierte El Texto En Mayusculas (Son Metodos De La Clase String)
print(Texto.upper())
print(Texto.lower())
# Find Busca Una Subcadena En Un Texto Y Devuelve La Posicion En La Que Se Encuentra.
print(Texto.find("M"))
# Replace Reemplaza Una Subcadena Por Otra En Un Texto.
print(Texto.replace("Mundo", "Python"))
# Devuelve True o False Si La Subcadena Se Encuentra En El Texto.
print("Mundo" in Texto)
# Find Es Un Indice Y In Es Un Booleano.